var game = {
    map: map,
    bgImage: s_mapBackground,
    MaxTank: 4,
    enemyTankType: [
        tankType.enemyTank.type2,
        tankType.enemyTank.type3,
        tankType.enemyTank.type4,
        tankType.enemyTank.type5,
        tankType.enemyTank.boss2,
        tankType.enemyTank.type6,
        tankType.enemyTank.type7,
        tankType.enemyTank.type8,
        tankType.enemyTank.type1,
        tankType.enemyTank.boss2,
        tankType.enemyTank.type2,
        tankType.enemyTank.type4,
        tankType.enemyTank.type6,
        tankType.enemyTank.type8,
        tankType.enemyTank.boss1,
        tankType.enemyTank.type1,
        tankType.enemyTank.type3,
        tankType.enemyTank.type5,
        tankType.enemyTank.type7,
        tankType.enemyTank.boss2,
        tankType.enemyTank.type1,
        tankType.enemyTank.type3,
        tankType.enemyTank.type6,
        tankType.enemyTank.type4,
        tankType.enemyTank.boss1,
        tankType.enemyTank.boss2,
    ],
    enemyTankNum: [2,2,2,2,1,2,2,2,2,1,2,2,2,2,1,2,2,2,2,1,1,1,1,1,2,2],
    itemType: [
        ItemAddPlayerHP,
        ItemAddPlayerHP,
        ItemAddTankSpeed,
        ItemAddTankSpeed,
        ItemFreeze,
        ItemDisplayInvisbleTank,
    ],
    itemPosition: [
        {x: 204, y: 280},
        {x: 570, y: 460},
        {x: 170, y: 560},
        {x: 460, y: 160},
        {x: 390, y: 400},
        {x: 600, y: 200},
    ],
}
